name: CI

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev, main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Web
        run: |
          cd apps/web
          npm install
          npm run build
          npm test --if-present

      - name: Build API
        run: |
          cd apps/api
          npm install
          npm run build
          npm test --if-present
